[tool.black]
line-length = 100
exclude = '(\.git|\.mypy_cache|venv)'
target-version = ['py311']

[tool.isort]
profile = 'black'

[tool.pytest.ini_options]
testpaths = ["tests"]

[[tool.mypy.overrides]]
ignore_missing_imports = true
